provider:
  name: faas
  gateway: http://localhost:8080

functions:
  # hotdog-classifier:
  #   lang: dockerfile
  #   handler: ./hotdog-classifier
  #   image: johnmccabe/hotdogclassifier:0.1

  hotdog-app:
    lang: go
    handler: ./hotdog-app
    image: johnmccabe/hotdogapp:0.1
    environment:
      classifier-url: /hotdog-classifier
      classifier-entity: hotdog
