provider:
  name: faas
  gateway: http://localhost:8080

functions:
  # hotdog-classifier:
  #   lang: dockerfile
  #   handler: ./hotdog-classifier
  #   image: johnmccabe/hotdogclassifier:0.1

  hotdog-app:
    lang: go
    handler: ./hotdog-app
    image: johnmccabe/hotdogapp:0.2
    environment:
      classifier_url: https://johnmccabe.get-faas.com/hotdog-classifier
      classifier_entity: hotdog
